// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_Desarrollador.Models.Db;

#nullable disable

namespace Prueba_Desarrollador.Migrations
{
    [DbContext(typeof(GestionBibliotecaContext))]
    partial class GestionBibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba_Desarrollador.Models.Db.Autore", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AutorId")
                        .HasName("PK__Autores__F58AE9091F2A03EA");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("Prueba_Desarrollador.Models.Db.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Libros__3214EC2725226FA1");

                    b.HasIndex("AutorId");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("Prueba_Desarrollador.Models.Db.Libro", b =>
                {
                    b.HasOne("Prueba_Desarrollador.Models.Db.Autore", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK_Libros_Autores");

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Prueba_Desarrollador.Models.Db.Autore", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
